import Nav from '@components/Nav/Nav'
import { Forum } from 'next/font/google'
import '@styles/global.scss'
import Footer from '@components/Footer/Footer'

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

const forum = Forum({
  weight: '400',
  subsets: ['latin'],
  variable: '--font-forum',
})

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={forum.variable}>
        <Nav />
        {children}
        <Footer />
      </body>
    </html>
  )
}
